#!/bin/bash

cd $PROJECT_ROOT
composer install
echo 'wp composer build success!!'
# deploy plugins to pantheon
# deploy theme to pantheon
ls web/ -al
npm install backstopjs || exit 0

echo -e "\nRunning backstop reference on ${DEV_SITE_URL}..."
backstop reference --config=$PROJECT_ROOT/scripts/github/test/backstopjs/backstopConfig.js

# Backstop test
echo -e "\nRunning backstop test on ${MULTIDEV_SITE_URL}..."
VISUAL_REGRESSION_RESULTS=$(backstop test --config=$PROJECT_ROOT/scripts/github/test/backstopjs/backstopConfig.js)

echo $VISUAL_REGRESSION_RESULTS
# execute backstopj
# deploy assets backstopjs

ls -al
