#!/bin/bash

cd $PROJECT_ROOT
composer install
echo 'wp composer build success!!'
# deploy plugins to pantheon
# deploy theme to pantheon
npm install backstopjs || exit 0

backstop -v
ls $PROJECT_ROOT/node_modules -al

$PROJECT_ROOT/node_modules/backstopjs/cli/index.js -v

echo -e "\nRunning backstop reference on ${DEV_SITE_URL}..."
$PROJECT_ROOT/node_modules/backstopjs/cli/index.js reference --config=$PROJECT_ROOT/scripts/github/test/backstopjs/backstopConfig.js

# Backstop test
echo -e "\nRunning backstop test on ${MULTIDEV_SITE_URL}..."
VISUAL_REGRESSION_RESULTS=$($PROJECT_ROOT/node_modules/backstopjs/cli/index.js test --config=$PROJECT_ROOT/scripts/github/test/backstopjs/backstopConfig.js)

$PROJECT_ROOT/node_modules/backstopjs/cli/index.js test --config=$PROJECT_ROOT/scripts/github/test/backstopjs/backstopConfig.js

/home/runner/terminus/vendor/bin/terminus auth:whoami

/home/runner/terminus/vendor/bin/terminus connection:set $PANTHEONSITENAME.$PANTHEONENV sftp
rsync -rLvz --size-only --ipv4 --progress -e 'ssh -p 2222' ./backstop_data/. --temp-dir=~/tmp/ $PANTHEONENV.$PANTHEONSITEUUID@appserver.$PANTHEONENV.$PANTHEONSITEUUID.drush.in:code/backstop_data/ --exclude='*.git*' --exclude node_modules/ --exclude gulp/ --exclude source/


# echo $VISUAL_REGRESSION_RESULTS
# execute backstopj
# deploy assets backstopjs

ls ./backstop_data -al
