#!/bin/bash

cd $PROJECT_ROOT
composer install
echo 'wp composer build success!!'
# deploy plugins to pantheon
# deploy theme to pantheon
npm install backstopjs || exit 0

backstop -v
ls $PROJECT_ROOT/node_modules -al

$PROJECT_ROOT/node_modules/backstopjs/cli/index.js -v

echo -e "\nRunning backstop reference on ${DEV_SITE_URL}..."
$PROJECT_ROOT/node_modules/backstopjs/cli/index.js reference --config=$PROJECT_ROOT/scripts/github/test/backstopjs/backstopConfig.js

# Backstop test
echo -e "\nRunning backstop test on ${MULTIDEV_SITE_URL}..."
VISUAL_REGRESSION_RESULTS=$($PROJECT_ROOT/node_modules/backstopjs/cli/index.js test --config=$PROJECT_ROOT/scripts/github/test/backstopjs/backstopConfig.js)

echo $VISUAL_REGRESSION_RESULTS
# execute backstopj
# deploy assets backstopjs

ls -al
