#!/bin/bash

printf "[\e[0;34mNOTICE\e[0m] Setting up SSH access to server.\n"
SSH_DIR="$HOME/.ssh"

mkdir -p "$SSH_DIR"
chmod 700 "$SSH_DIR"
touch "$SSH_DIR/id_rsa1"
echo "$SSH_DIR/id_rsa1"
echo "${{ secrets.STAGING_PRIVATE_KEY }}"
echo "${{ secrets.STAGING_PRIVATE_KEY }}" > "$SSH_DIR/id_rsa1"
chmod 600 "$SSH_DIR/id_rsa1"
eval "$(ssh-agent -s)"
ssh-add "$SSH_DIR/id_rsa1"
ssh-add -l
echo "SSH PRIVATE KEY IMPORTED!!!"