name: Pantheon Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup SSH access to Pantheon
      run: |
        ls -al
        eval $(ssh-agent -s) #ok
        mkdir -p ~/.ssh #ok
        export PATH="$PATH:$COMPOSER_HOME/vendor/bin"
        export PROJECT_ROOT="$(pwd)"
        export HTDOCS="$HOME/htdocs"
        export GITHUB_BRANCH=${GITHUB_REF##*heads/}
        echo GITHUB_BRANCH
        export PANTHEONEMAIL="cralberto11@gmail.com"
        export PANTHEONSITENAME="carltest1"
        export PANTHEONSITEUUID="01507cf9-d5e7-460d-83ee-5587a03e7d9a"
        export PANTHEONENV="dev"
        export STAGING_PRIVATE_KEY=${{ secrets.STAGING_PRIVATE_KEY }}

        sh $PROJECT_ROOT/scripts/github/setup-ssh

        mkdir ~/terminus
        cd ~/terminus
        curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install || exit 0
        # composer global require consolidation/cgr
        # cgr --stability RC pantheon-systems/terminus
        npm -v
        cd ~
        ls -al
        /home/runner/terminus/vendor/bin/terminus self:info
        /home/runner/terminus/vendor/bin/terminus auth:login --machine-token="${{ secrets.MACHINETOKEN }}"
        /home/runner/terminus/vendor/bin/terminus auth:login --email="$PANTHEONEMAIL"
        /home/runner/terminus/vendor/bin/terminus auth:whoami
        echo $PROJECT_ROOT
        cd $PROJECT_ROOT 
        composer install
        ls web -al   
        ls web/wp -al
        npm install -g backstopjs




    # - name: ssh-add 2 method
    #   uses: webfactory/ssh-agent@v0.1.1
    #   with:
    #       STAGING_PRIVATE_KEY: ${{ secrets.STAGING_PRIVATE_KEY }}

    # - name: Run WP composer build
    #   run: |
    #     ssh-add -l
    #     echo Add other actions to build,
    #     echo test, and deploy your project.
    #     composer update
    #     ls web -al   
    #     ls web/wp -al

    - name: Run WP Visual regression test
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        composer update
        ls web -al   
        ls web/wp -al
        ls -al
        npm -v
        npm install -g backstopjs

